baseURL = "/"
languageCode = "en-us"
title = "Araw Seekers"

[permalinks]
	blog = "/:filename/"

[frontmatter]
	date = ["date", "publishDate"]

[params]
	homeText = "(A)typical Experiences via Photosynthesis"
	dateFormat = "2006 Jan 2"

[menu]
	[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
	[[menu.main]]

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		disable = true
	[privacy.instagram]
		disable = true
	[privacy.twitter]
		disable = true
	[privacy.vimeo]
		disable = true
	[privacy.youtube]
		disable = false
		privacyEnhanced = true

